---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anonymous.
--- DateTime: 12/6/2025 8:59 AM
---
-- scripts/items.lua
Items = {
    [1] = {
        name = "Iron Sword",
        spriteId = 101,
        class = 1, -- 1=weapon, 2=armor, 3=consumable
        group = 1, -- 1=sword, 2=axe, etc
        damage = 15,
        value = 100
    },
    [2] = {
        name = "Health Potion",
        spriteId = 201,
        class = 3,
        group = 1, -- potions
        effect = 1, -- 1=heal
        power = 50,
        value = 25
    },
    [3] = {
        name = "Leather Armor",
        spriteId = 301,
        class = 2,
        group = 1, -- light armor
        defense = 10,
        value = 75
    },
}

function GetItem(id)
    return Items[id]
end

function GetItemName(id)
    local item = Items[id]
    return item and item.name or "Unknown"
end

log("[LUA] Items loaded: " .. #Items)