---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Anonymous.
--- DateTime: 12/6/2025 9:01 AM
---
-- scripts/spells.lua
Spells = {
    [1] = {
        name = "Fireball",
        spriteId = 401,
        group = 1, -- offensive
        effect = 1, -- damage
        power = 30,
        manaCost = 15
    },
    [2] = {
        name = "Heal",
        spriteId = 402,
        group = 2, -- support
        effect = 2, -- heal
        power = 40,
        manaCost = 20
    },
    [3] = {
        name = "Haste",
        spriteId = 403,
        group = 3, -- buff
        effect = 3, -- speed boost
        duration = 30,
        manaCost = 25
    },
}

function GetSpell(id)
    return Spells[id]
end

log("[LUA] Spells loaded: " .. #Spells)